
export const Users = [
    {
        id: 1,
        profilePic : "https://i.pinimg.com/736x/82/9b/d3/829bd30ab1812afc1da4df61ecfb55be.jpg",
        username: "Olivia",
        active: true,
    },
    {
        id: 2,
        profilePic : "https://i.pinimg.com/736x/c2/51/80/c25180669d2404322b44e3adca7a6ed2.jpg",
        username: "Emma",
        active: true,
    },
    {
        id: 3,
        profilePic : "https://images-cdn.ubuy.co.in/633b5ff554c9b030693370a8-aruno-maison-1j-1bs-sexy-girl-2-sexy.jpg",
        username: "Aachal",
        active: true,
    },
    {
        id: 4,
        profilePic : "https://i0.wp.com/sguru.org/wp-content/uploads/2017/06/5204845_orig.jpg?resize=433%2C519&ssl=1",
        username: "Arti Singh",
        active: true,
    },
    {
        id: 5,
        profilePic : "https://sexyphoto.es/wp-content/uploads/2021/03/boobs-girls-hot-teens-prefect-ass-legs10.jpg",
        username: "Anika rajput",
        active: false,
    },
    {
        id: 6,
        profilePic : "https://in-static.ok-img.com/uploads/in/22/11/28/ewfcby8rmuefoqn0dyi5u05obo1gyfmq.jpg",
        username: "Leena",
         active: false,
    },
    {
        id: 7,
        profilePic : "https://in-static.ok-img.com/uploads/in/23/02/15/x9tckdpq2m7m68cte3lb58ivzcisgy6w.jpg",
        username: "Ikshita",
         active: false,
    },
    {
        id: 8,
        profilePic : "https://dp.profilepics.in/dp/2022/hot-girl-dp/hot-girl-photo-dp-10.jpg",
        username: "Isha",
         active: false,
    },
    {
        id: 9,
        profilePic : "https://phreesite.com/wp-content/uploads/2020/09/Sarah-Magusara-profile-1.jpg",
        username: "Gautami",
         active: false,
    },
    {
        id: 10,
        profilePic : "https://st1.photogallery.ind.sh/wp-content/uploads/indiacom/check-out-british-model-demi-rose-hot-sexy-latest-photos-2021-202002-1622985520.jpg",
        username: "Falak",
        active: false,
    },
    {
        id: 11,
        profilePic : "https://st1.photogallery.ind.sh/wp-content/uploads/indiacom/demi-rose-sets-internet-on-fire-202105-1619882294.jpg?impolicy=Medium_Widthonly&w=450",
        username: "Ekta",
         active: false,
    },
    {
        id: 12,
        profilePic : "https://i.pinimg.com/736x/c6/09/c0/c609c0d64af46881b569e003e0bc2928.jpg",
        username: "Chandani",
        active: true,
    },
    {
        id: 13,
        profilePic : "https://st4.depositphotos.com/19688680/21963/i/600/depositphotos_219638316-stock-photo-attractive-topless-indian-woman-white.jpg",
        username: "Anya",
        active: true,
    },
]

export const Posts = [
    {
        id: 1,
        desc: "Wants to play with Me !!!",
        photo: "https://dwgyu36up6iuz.cloudfront.net/heru80fdn/image/upload/c_fill,d_placeholder_gq.png,fl_progressive,g_face,h_1080,q_80,w_1920/v1424905885/gq_how-to-date-a-super-hot-girl.jpg",
        date: "10 min ago",
        userId : 1,
        likes : 355,
        comment : 96,
    },
    {
        id: 2,
        desc: "",
        photo: "https://kissbrides.com/otassesi/2022/05/indian-sexy-girls-scaled.jpg",
        date: "",
        userId :2,
        likes : 65,
        comment : 58,
    },
    {
        id: 3,
        desc: "My sexy Pic",
        photo: "https://i0.wp.com/i.imgur.com/mqGCtyp.jpg?resize=640%2C9999&ssl=1",
        date: "",
        userId : 3,
        likes : 95,
        comment : 26,
    },
    {
        id: 4,
        desc: "I am hot Today",
        photo: "https://media.theeverygirl.com/wp-content/uploads/2022/04/hot-girl-summer-3.jpg",
        date: "",
        userId : 4,
        likes : 95,
        comment : 6,
    },
    {
        id: 5,
        desc: "",
        photo: "https://images.news18.com/ibnlive/uploads/2021/01/1610697426_Niddhi-Aggarwal-df-1.jpg?im=FitAndFill,width=1200,height=1200",
        date: "",
        userId : 5,
        likes : 35,
        comment : 6,
    },
    {
        id: 6,
        desc: "",
        photo:"https://images-na.ssl-images-amazon.com/images/I/71DQQ3ocHkL.jpg",
        date: "",
        userId : 6,
        likes : 55,
        comment : 6,
    },
]